USE lubyconuser;

INSERT INTO `Country` SET `name` = 'Afghanistan', `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Albania', `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Algeria', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'American Samoa', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Andorra', `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Angola', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Anguilla', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Antarctica', `continent`='undecided', `region`='undecided';
INSERT INTO `Country` SET `name` = 'Antigua and Barbuda', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Argentina',`continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Armenia', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Aruba', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Australia',`continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Austria', `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Azerbaijan',`continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Bahamas', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Bahrain', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Bangladesh', `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Barbados', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Belarus', `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Belgium', `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Belize', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Benin', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Bermuda', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Bhutan', `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Bolivia', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Bosnia and Herzegovina',`continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Botswana', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Brazil', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'British Indian Ocean Territory', `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'British Virgin Islands',`continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Brunei', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Bulgaria',`continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Burkina Faso', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Burundi',`continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Cambodia', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Cameroon', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Canada', `continent`='americas', `region`='north_america';
INSERT INTO `Country` SET `name` = 'Cape Verde', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Cayman Islands', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Central African Republic',`continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Chad',`continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Chile', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'China', `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Christmas Island', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Cocos Islands', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Colombia', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Comoros', `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Cook Islands', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Costa Rica', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Croatia', `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Cuba', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Curacao', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Cyprus', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Czech Republic', `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Democratic Republic of the Congo', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Denmark', `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Djibouti',`continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Dominica', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Dominican Republic', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'East Timor', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Ecuador',`continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Egypt', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'El Salvador', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Equatorial Guinea', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Eritrea', `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Estonia', `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Ethiopia', `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Falkland Islands', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Faroe Islands', `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Fiji', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Finland', `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'France', `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'French Guiana', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'French polynesia', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Gabon', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Gambia', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Georgia', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Germany', `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Ghana', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Gibraltar', `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Greece', `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Greenland', `continent`='americas', `region`='north_america';
INSERT INTO `Country` SET `name` = 'Grenada', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Guam', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Guatemala', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Guernsey', `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Guinea', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Guinea-Bissau', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Guyana', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Haiti', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Honduras', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Hong Kong',`continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Hungary', `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Iceland', `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'India', `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Indonesia', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Iran', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Iraq', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Ireland',`continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Isle of Man',`continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Israel',`continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Italy', `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Ivory Coast', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Jamaica', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Japan',`continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Jersey',`continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Jordan', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Kazakhstan', `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Kenya', `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Kiribati', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Kosovo', `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Kuwait', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Kyrgyzstan', `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Laos', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Latvia',`continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Lebanon',`continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Lesotho', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Liberia', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Libya', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Liechtenstein', `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Lithuania', `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Luxembourg', `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Macao', `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Macedonia', `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Madagascar', `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Malawi', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Malaysia',`continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Maldives',`continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Mali', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Malta', `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Marshall Islands', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Mauritania',`continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Mauritius', `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Mayotte', `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Mexico', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Micronesia', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Moldova', `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Monaco', `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Mongolia',`continent`='asia', `region`='northern_asia';
INSERT INTO `Country` SET `name` = 'Montenegro', `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Montserrat', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Morocco', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Mozambique', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Myanmar',`continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Namibia', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Nauru', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Nepal', `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Netherlands',`continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Netherlands Antilles', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'New Caledonia', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'New Zealand', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Nicaragua', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Niger', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Nigeria',`continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Niue', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'North Korea',`continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Northern Mariana Islands',`continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Norway', `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Oman', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Pakistan', `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Palau', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Palestine', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Panama', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Papua New Guinea', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Paraguay', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Peru', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Philippines',`continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Pitcairn', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Poland', `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Portugal', `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Puerto Rico', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Qatar', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Republic of the Congo', `continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Reunion', `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Romania', `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Russia', `continent`='asia', `region`='northern_asia';
INSERT INTO `Country` SET `name` = 'Rwanda', `continent`='africa', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Saint Barthelemy', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Saint Helena', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Saint Kitts and Nevis', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Saint Lucia', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Saint Martin',`continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Saint Pierre and Miquelon', `continent`='americas', `region`='northern_america';
INSERT INTO `Country` SET `name` = 'Saint Vincent and the Grenadines', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Samoa', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'San Marino', `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Sao Tome and Principe', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Saudi Arabia', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Senegal',`continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Serbia', `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Seychelles', `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Sierra Leone', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Singapore', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Sint Maarten', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Slovakia', `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Slovenia', `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Solomon Islands', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Somalia', `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'South Africa', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'South Korea', `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'South Sudan', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Spain', `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Sri Lanka', `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Sudan', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Suriname', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Svalbard and Jan Mayen', `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Swaziland', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Sweden', `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Switzerland', `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Syria', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Taiwan', `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Tajikistan', `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Tanzania', `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Thailand', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Togo', `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Tokelau', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Tonga', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Trinidad and Tobago', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Tunisia', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Turkey', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Turkmenistan',`continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Turks and Caicos Islands', `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Tuvalu', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'U.S. Virgin Islands', `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Uganda', `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Ukraine', `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'United Arab Emirates', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'United Kingdom', `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'United States', `continent`='americas', `region`='north_america';
INSERT INTO `Country` SET `name` = 'Uruguay', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Uzbekistan', `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Vanuatu', `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Vatican', `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Venezuela', `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Vietnam', `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Wallis and Futuna',`continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Western Sahara', `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Yemen', `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Zambia', `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Zimbabwe',`continent`='africa', `region`='southern_africa';