USE lubyconuser;

INSERT INTO `Country` SET `name` = 'Afghanistan', `utc` = 4, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Albania', `utc` = 1, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Algeria', `utc` = 1, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'American Samoa', `utc` = -11, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Andorra', `utc` = 1, `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Angola', `utc` = 1, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Anguilla', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Antarctica', `utc` = 0, `continent`='undecided', `region`='undecided';
INSERT INTO `Country` SET `name` = 'Antigua and Barbuda', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Argentina', `utc` = -3, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Armenia', `utc` = 4, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Aruba', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Australia', `utc` = 10, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Austria', `utc` = 1, `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Azerbaijan', `utc` = 4, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Bahamas', `utc` = -5, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Bahrain', `utc` = 3, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Bangladesh', `utc` = 6, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Barbados', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Belarus', `utc` = 3, `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Belgium', `utc` = 1, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Belize', `utc` = -6, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Benin', `utc` = 1, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Bermuda', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Bhutan', `utc` = 6, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Bolivia', `utc` = -4, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Bosnia and Herzegovina',`utc` = 1, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Botswana', `utc` = 2, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Brazil', `utc` = -3, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'British Indian Ocean Territory', `utc` = 6, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'British Virgin Islands', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Brunei', `utc` = 8, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Bulgaria', `utc` = 2, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Burkina Faso', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Burundi', `utc` = 2, `continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Cambodia', `utc` = 7, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Cameroon', `utc` = 1, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Canada', `utc` = -5, `continent`='americas', `region`='north_america';
INSERT INTO `Country` SET `name` = 'Cape Verde', `utc` = -1, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Cayman Islands', `utc` = -5, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Central African Republic', `utc` = 1, `continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Chad', `utc` = 1, `continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Chile', `utc` = -4, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'China', `utc` = 8, `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Christmas Island', `utc` = 7, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Cocos Islands', `utc` = 6, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Colombia', `utc` = -5, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Comoros', `utc` = 3, `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Cook Islands', `utc` = -10, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Costa Rica', `utc` = -6, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Croatia', `utc` = 1, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Cuba', `utc` = -5, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Curacao', `utc` = -4, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Cyprus', `utc` = 2, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Czech Republic', `utc` = 1, `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Democratic Republic of the Congo', `utc` = 1, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Denmark', `utc` = 1, `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Djibouti', `utc` = 3, `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Dominica', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Dominican Republic', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'East Timor', `utc` = 9, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Ecuador', `utc` = -5, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Egypt', `utc` = 2, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'El Salvador', `utc` = -6, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Equatorial Guinea', `utc` = 1, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Eritrea', `utc` = 3, `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Estonia', `utc` = 2, `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Ethiopia', `utc` = 3, `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Falkland Islands', `utc` = -3, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Faroe Islands', `utc` = 0, `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Fiji', `utc` = 12, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Finland', `utc` = 2, `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'France', `utc` = 1, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'French Guiana', `utc` = -3, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'French polynesia', `utc` = -10, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Gabon', `utc` = 1, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Gambia', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Georgia', `utc` = 4, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Germany', `utc` = 1, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Ghana', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Gibraltar', `utc` = 1, `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Greece', `utc` = 2, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Greenland', `utc` = -4, `continent`='americas', `region`='north_america';
INSERT INTO `Country` SET `name` = 'Grenada', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Guam', `utc` = 10, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Guatemala', `utc` = -6, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Guernsey', `utc` = 0, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Guinea', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Guinea-Bissau', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Guyana', `utc` = -4, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Haiti', `utc` = -5, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Honduras', `utc` = -6, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Hong Kong', `utc` = 8, `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Hungary', `utc` = 1, `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Iceland', `utc` = 0, `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'India', `utc` = 5, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Indonesia', `utc` = 7, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Iran', `utc` = 3, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Iraq', `utc` = 3, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Ireland', `utc` = 0, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Isle of Man', `utc` = 0, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Israel', `utc` = 2, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Italy', `utc` = 1, `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Ivory Coast', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Jamaica', `utc` = -5, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Japan', `utc` = 9, `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Jersey', `utc` = 0, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Jordan', `utc` = 2, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Kazakhstan', `utc` = 5, `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Kenya', `utc` = 3, `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Kiribati', `utc` = 12, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Kosovo', `utc` = 1, `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Kuwait', `utc` = 3, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Kyrgyzstan', `utc` = 6, `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Laos', `utc` = 7, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Latvia', `utc` = 2, `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Lebanon', `utc` = 2, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Lesotho', `utc` = 2, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Liberia', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Libya', `utc` = 2, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Liechtenstein', `utc` = 1, `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Lithuania', `utc` = 2, `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Luxembourg', `utc` = 1, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Macao', `utc` = 8, `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Macedonia', `utc` = 1, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Madagascar', `utc` = 3, `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Malawi', `utc` = 2, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Malaysia', `utc` = 8, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Maldives', `utc` = 5, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Mali', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Malta', `utc` = 1, `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Marshall Islands', `utc` = 12, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Mauritania', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Mauritius', `utc` = 4, `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Mayotte', `utc` = 3, `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Mexico', `utc` = -6, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Micronesia', `utc` = 11, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Moldova', `utc` = 2, `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Monaco', `utc` = 1, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Mongolia', `utc` = 7, `continent`='asia', `region`='northern_asia';
INSERT INTO `Country` SET `name` = 'Montenegro', `utc` = 1, `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Montserrat', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Morocco', `utc` = 0, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Mozambique', `utc` = 2, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Myanmar', `utc` = 6, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Namibia', `utc` = 1, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Nauru', `utc` = 12, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Nepal', `utc` = 6, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Netherlands', `utc` = 1, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'Netherlands Antilles', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'New Caledonia', `utc` = 11, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'New Zealand', `utc` = -11, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Nicaragua', `utc` = -6, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Niger', `utc` = 1, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Nigeria', `utc` = 1, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Niue', `utc` = -11, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'North Korea', `utc` = 8, `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Northern Mariana Islands', `utc` = 10, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Norway', `utc` = 1, `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Oman', `utc` = 4, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Pakistan', `utc` = 5, `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Palau', `utc` = 9, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Palestine', `utc` = 2, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Panama', `utc` = -5, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Papua New Guinea', `utc` = 10, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Paraguay', `utc` = -4, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Peru', `utc` = -5, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Philippines', `utc` = 8, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Pitcairn', `utc` = -8, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Poland', `utc` = 1, `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'Portugal', `utc` = -1, `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Puerto Rico', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Qatar', `utc` = 3, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Republic of the Congo', `utc` = 1, `continent`='africa', `region`='central_africa';
INSERT INTO `Country` SET `name` = 'Reunion', `utc` = 4, `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Romania', `utc` = 2, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Russia', `utc` = 3, `continent`='asia', `region`='northern_asia';
INSERT INTO `Country` SET `name` = 'Rwanda', `utc` = 2, `continent`='africa', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Saint Barthelemy', `utc` = -4, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Saint Helena', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Saint Kitts and Nevis', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Saint Lucia', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Saint Martin', `utc` = -4, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Saint Pierre and Miquelon', `utc` = -3, `continent`='americas', `region`='northern_america';
INSERT INTO `Country` SET `name` = 'Saint Vincent and the Grenadines', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Samoa', `utc` = 13, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'San Marino', `utc` = 1, `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Sao Tome and Principe', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Saudi Arabia', `utc` = 3, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Senegal', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Serbia', `utc` = 1, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Seychelles', `utc` = 4, `continent`='africa', `region`='indian_ocean';
INSERT INTO `Country` SET `name` = 'Sierra Leone', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Singapore', `utc` = 8, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Sint Maarten', `utc` = -4, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Slovakia', `utc` = 1, `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Slovenia', `utc` = 1, `continent`='europe', `region`='south_east_europe';
INSERT INTO `Country` SET `name` = 'Solomon Islands', `utc` = 11, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Somalia', `utc` = 3, `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'South Africa', `utc` = 2, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'South Korea', `utc` = 9, `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'South Sudan', `utc` = 3, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Spain', `utc` = 1, `continent`='europe', `region`='south_west_europe';
INSERT INTO `Country` SET `name` = 'Sri Lanka', `utc` = 5, `continent`='asia', `region`='south_asia';
INSERT INTO `Country` SET `name` = 'Sudan', `utc` = 3, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Suriname', `utc` = -3, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Svalbard and Jan Mayen', `utc` = 1, `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Swaziland', `utc` = 2, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Sweden', `utc` = 1, `continent`='europe', `region`='northern_europe';
INSERT INTO `Country` SET `name` = 'Switzerland', `utc` = 1, `continent`='europe', `region`='central_europe';
INSERT INTO `Country` SET `name` = 'Syria', `utc` = 2, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Taiwan', `utc` = 8, `continent`='asia', `region`='east_asia';
INSERT INTO `Country` SET `name` = 'Tajikistan', `utc` = 5, `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Tanzania', `utc` = 3, `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Thailand', `utc` = 7, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Togo', `utc` = 0, `continent`='africa', `region`='western_africa';
INSERT INTO `Country` SET `name` = 'Tokelau', `utc` = 13, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Tonga', `utc` = 13, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Trinidad and Tobago', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Tunisia', `utc` = 1, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Turkey', `utc` = 2, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Turkmenistan', `utc` = 5, `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Turks and Caicos Islands', `utc` = -4, `continent`='americas', `region`='west_indies';
INSERT INTO `Country` SET `name` = 'Tuvalu', `utc` = 12, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'U.S. Virgin Islands', `utc` = -4, `continent`='americas', `region`='central_america';
INSERT INTO `Country` SET `name` = 'Uganda', `utc` = 3, `continent`='africa', `region`='eastern_africa';
INSERT INTO `Country` SET `name` = 'Ukraine', `utc` = 3, `continent`='europe', `region`='eastern_europe';
INSERT INTO `Country` SET `name` = 'United Arab Emirates', `utc` = 4, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'United Kingdom', `utc` = 0, `continent`='europe', `region`='western_europe';
INSERT INTO `Country` SET `name` = 'United States', `utc` = -5, `continent`='americas', `region`='north_america';
INSERT INTO `Country` SET `name` = 'Uruguay', `utc` = -3, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Uzbekistan', `utc` = 5, `continent`='asia', `region`='central_asia';
INSERT INTO `Country` SET `name` = 'Vanuatu', `utc` = 11, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Vatican', `utc` = 1, `continent`='europe', `region`='southern_europe';
INSERT INTO `Country` SET `name` = 'Venezuela', `utc` = -4, `continent`='americas', `region`='south_america';
INSERT INTO `Country` SET `name` = 'Vietnam', `utc` = 7, `continent`='asia', `region`='south_east_asia';
INSERT INTO `Country` SET `name` = 'Wallis and Futuna', `utc` = 12, `continent`='oceania', `region`='pacific';
INSERT INTO `Country` SET `name` = 'Western Sahara', `utc` = 0, `continent`='africa', `region`='northern_africa';
INSERT INTO `Country` SET `name` = 'Yemen', `utc` = 3, `continent`='asia', `region`='south_west_asia';
INSERT INTO `Country` SET `name` = 'Zambia', `utc` = 2, `continent`='africa', `region`='southern_africa';
INSERT INTO `Country` SET `name` = 'Zimbabwe', `utc` = 2, `continent`='africa', `region`='southern_africa';