USE lubycon;

INSERT INTO `luby_country` SET `country_name` = 'Afghanistan', `country_tel_one` = '+93', `continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Albania', `country_tel_one` = '+355', `continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Algeria', `country_tel_one` = '+213', `continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'American Samoa', `country_tel_one` = '+1-684', `continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Andorra', `country_tel_one` = '+376', `continent`='europe', `region`='south_west_europe';
INSERT INTO `luby_country` SET `country_name` = 'Angola', `country_tel_one` = '+244', `continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Anguilla', `country_tel_one` = '+1-264',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Antarctica', `country_tel_one` = '+672',`continent`='undecided', `region`='undecided';
INSERT INTO `luby_country` SET `country_name` = 'Antigua and Barbuda', `country_tel_one` = '+1-268',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Argentina', `country_tel_one` = '+54',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Armenia', `country_tel_one` = '+374',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Aruba', `country_tel_one` = '+297',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Australia', `country_tel_one` = '+61',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Austria', `country_tel_one` = '+43',`continent`='europe', `region`='central_europe';
INSERT INTO `luby_country` SET `country_name` = 'Azerbaijan', `country_tel_one` = '+994',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Bahamas', `country_tel_one` = '+1-242',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Bahrain', `country_tel_one` = '+973',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Bangladesh', `country_tel_one` = '+880',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Barbados', `country_tel_one` = '+1-246',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Belarus', `country_tel_one` = '+375',`continent`='europe', `region`='eastern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Belgium', `country_tel_one` = '+32',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Belize', `country_tel_one` = '+501',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Benin', `country_tel_one` = '+229',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Bermuda', `country_tel_one` = '+1-441',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Bhutan', `country_tel_one` = '+975',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Bolivia', `country_tel_one` = '+591',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Bosnia and Herzegovina', `country_tel_one` = '+387',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Botswana', `country_tel_one` = '+267',`continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Brazil', `country_tel_one` = '+55',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'British Indian Ocean Territory', `country_tel_one` = '+246',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'British Virgin Islands', `country_tel_one` = '+1-284',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Brunei', `country_tel_one` = '+673',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Bulgaria', `country_tel_one` = '+359',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Burkina Faso', `country_tel_one` = '+226',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Burundi', `country_tel_one` = '+257',`continent`='africa', `region`='central_africa';
INSERT INTO `luby_country` SET `country_name` = 'Cambodia', `country_tel_one` = '+855',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Cameroon', `country_tel_one` = '+237',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Canada', `country_tel_one` = '+1',`continent`='americas', `region`='north_america';
INSERT INTO `luby_country` SET `country_name` = 'Cape Verde', `country_tel_one` = '+238',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Cayman Islands', `country_tel_one` = '+1-345',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Central African Republic', `country_tel_one` = '+236',`continent`='africa', `region`='central_africa';
INSERT INTO `luby_country` SET `country_name` = 'Chad', `country_tel_one` = '+235',`continent`='africa', `region`='central_africa';
INSERT INTO `luby_country` SET `country_name` = 'Chile', `country_tel_one` = '+56',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'China', `country_tel_one` = '+86',`continent`='asia', `region`='east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Christmas Island', `country_tel_one` = '+61',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Cocos Islands', `country_tel_one` = '+61',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Colombia', `country_tel_one` = '+57',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Comoros', `country_tel_one` = '+269',`continent`='africa', `region`='indian_ocean';
INSERT INTO `luby_country` SET `country_name` = 'Cook Islands', `country_tel_one` = '+682',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Costa Rica', `country_tel_one` = '+506',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Croatia', `country_tel_one` = '+385',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Cuba', `country_tel_one` = '+53',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Curacao', `country_tel_one` = '+599',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Cyprus', `country_tel_one` = '+357',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Czech Republic', `country_tel_one` = '+420',`continent`='europe', `region`='central_europe';
INSERT INTO `luby_country` SET `country_name` = 'Democratic Republic of the Congo', `country_tel_one` = '+243',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Denmark', `country_tel_one` = '+45',`continent`='europe', `region`='northern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Djibouti', `country_tel_one` = '+253',`continent`='africa', `region`='eastern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Dominica', `country_tel_one` = '+1-767',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Dominican Republic', `country_tel_one` = '+1-809', `country_tel_two` ='+1-827', `country_tel_three` ='+1-849',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'East Timor', `country_tel_one` = '+670',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Ecuador', `country_tel_one` = '+593',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Egypt', `country_tel_one` = '+20',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'El Salvador', `country_tel_one` = '+503',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Equatorial Guinea', `country_tel_one` = '+240',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Eritrea', `country_tel_one` = '+291',`continent`='africa', `region`='eastern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Estonia', `country_tel_one` = '+372',`continent`='europe', `region`='eastern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Ethiopia', `country_tel_one` = '+251',`continent`='africa', `region`='eastern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Falkland Islands', `country_tel_one` = '+500',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Faroe Islands', `country_tel_one` = '+298',`continent`='europe', `region`='northern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Fiji', `country_tel_one` = '+679',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Finland', `country_tel_one` = '+358',`continent`='europe', `region`='northern_europe';
INSERT INTO `luby_country` SET `country_name` = 'France', `country_tel_one` = '+33',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'French Guiana', `country_tel_one` = '+594',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'French polynesia', `country_tel_one` = '+689',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Gabon', `country_tel_one` = '+241',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Gambia', `country_tel_one` = '+220',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Georgia', `country_tel_one` = '+995',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Germany', `country_tel_one` = '+49',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Ghana', `country_tel_one` = '+233',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Gibraltar', `country_tel_one` = '+350',`continent`='europe', `region`='south_west_europe';
INSERT INTO `luby_country` SET `country_name` = 'Greece', `country_tel_one` = '+30',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Greenland', `country_tel_one` = '+299',`continent`='americas', `region`='north_america';
INSERT INTO `luby_country` SET `country_name` = 'Grenada', `country_tel_one` = '+1-473',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Guam', `country_tel_one` = '+1-671',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Guatemala', `country_tel_one` = '+502',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Guernsey', `country_tel_one` = '+44-1481',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Guinea', `country_tel_one` = '+224',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Guinea-Bissau', `country_tel_one` = '+245',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Guyana', `country_tel_one` = '+592',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Haiti', `country_tel_one` = '+509',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Honduras', `country_tel_one` = '+504',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Hong Kong', `country_tel_one` = '+852',`continent`='asia', `region`='east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Hungary', `country_tel_one` = '+36',`continent`='europe', `region`='central_europe';
INSERT INTO `luby_country` SET `country_name` = 'Iceland', `country_tel_one` = '+354',`continent`='europe', `region`='northern_europe';
INSERT INTO `luby_country` SET `country_name` = 'India', `country_tel_one` = '+91',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Indonesia', `country_tel_one` = '+62',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Iran', `country_tel_one` = '+98',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Iraq', `country_tel_one` = '+964',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Ireland', `country_tel_one` = '+353',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Isle of Man', `country_tel_one` = '+44-1624',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Israel', `country_tel_one` = '+972',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Italy', `country_tel_one` = '+39',`continent`='europe', `region`='southern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Ivory Coast', `country_tel_one` = '+225',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Jamaica', `country_tel_one` = '+1-876',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Japan', `country_tel_one` = '+81',`continent`='asia', `region`='east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Jersey', `country_tel_one` = '+44-1534',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Jordan', `country_tel_one` = '+962',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Kazakhstan', `country_tel_one` = '+7',`continent`='asia', `region`='central_asia';
INSERT INTO `luby_country` SET `country_name` = 'Kenya', `country_tel_one` = '+254',`continent`='africa', `region`='eastern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Kiribati', `country_tel_one` = '+686',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Kosovo', `country_tel_one` = '+383',`continent`='europe', `region`='southern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Kuwait', `country_tel_one` = '+965',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Kyrgyzstan', `country_tel_one` = '+996',`continent`='asia', `region`='central_asia';
INSERT INTO `luby_country` SET `country_name` = 'Laos', `country_tel_one` = '+856',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Latvia', `country_tel_one` = '+371',`continent`='europe', `region`='eastern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Lebanon', `country_tel_one` = '+961',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Lesotho', `country_tel_one` = '+266',`continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Liberia', `country_tel_one` = '+231',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Libya', `country_tel_one` = '+218',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Liechtenstein', `country_tel_one` = '+423',`continent`='europe', `region`='central_europe';
INSERT INTO `luby_country` SET `country_name` = 'Lithuania', `country_tel_one` = '+370',`continent`='europe', `region`='eastern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Luxembourg', `country_tel_one` = '+352',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Macao', `country_tel_one` = '+853',`continent`='asia', `region`='east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Macedonia', `country_tel_one` = '+389',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Madagascar', `country_tel_one` = '+261',`continent`='africa', `region`='indian_ocean';
INSERT INTO `luby_country` SET `country_name` = 'Malawi', `country_tel_one` = '+265',`continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Malaysia', `country_tel_one` = '+60',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Maldives', `country_tel_one` = '+960',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Mali', `country_tel_one` = '+223',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Malta', `country_tel_one` = '+356',`continent`='europe', `region`='southern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Marshall Islands', `country_tel_one` = '+692',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Mauritania', `country_tel_one` = '+222',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Mauritius', `country_tel_one` = '+230',`continent`='africa', `region`='indian_ocean';
INSERT INTO `luby_country` SET `country_name` = 'Mayotte', `country_tel_one` = '+262',`continent`='africa', `region`='indian_ocean';
INSERT INTO `luby_country` SET `country_name` = 'Mexico', `country_tel_one` = '+52',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Micronesia', `country_tel_one` = '+691',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Moldova', `country_tel_one` = '+373',`continent`='europe', `region`='eastern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Monaco', `country_tel_one` = '+377',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Mongolia', `country_tel_one` = '+969',`continent`='asia', `region`='northern_asia';
INSERT INTO `luby_country` SET `country_name` = 'Montenegro', `country_tel_one` = '+382',`continent`='europe', `region`='southern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Montserrat', `country_tel_one` = '+1-664',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Morocco', `country_tel_one` = '+212',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Mozambique', `country_tel_one` = '+258',`continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Myanmar', `country_tel_one` = '+95',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Namibia', `country_tel_one` = '+264',`continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Nauru', `country_tel_one` = '+674',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Nepal', `country_tel_one` = '+977',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Netherlands', `country_tel_one` = '+31',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'Netherlands Antilles', `country_tel_one` = '+599',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'New Caledonia', `country_tel_one` = '+687',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'New Zealand', `country_tel_one` = '+64',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Nicaragua', `country_tel_one` = '+505',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Niger', `country_tel_one` = '+227',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Nigeria', `country_tel_one` = '+234',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Niue', `country_tel_one` = '+683',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'North Korea', `country_tel_one` = '+850',`continent`='asia', `region`='east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Northern Mariana Islands', `country_tel_one` = '+1-670',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Norway', `country_tel_one` = '+47',`continent`='europe', `region`='northern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Oman', `country_tel_one` = '+968',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Pakistan', `country_tel_one` = '+92',`continent`='asia', `region`='central_asia';
INSERT INTO `luby_country` SET `country_name` = 'Palau', `country_tel_one` = '+680',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Palestine', `country_tel_one` = '+970',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Panama', `country_tel_one` = '+507',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Papua New Guinea', `country_tel_one` = '+675',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Paraguay', `country_tel_one` = '+595',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Peru', `country_tel_one` = '+51',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Philippines', `country_tel_one` = '+63',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Pitcairn', `country_tel_one` = '+64',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Poland', `country_tel_one` = '+48',`continent`='europe', `region`='eastern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Portugal', `country_tel_one` = '+351',`continent`='europe', `region`='south_west_europe';
INSERT INTO `luby_country` SET `country_name` = 'Puerto Rico', `country_tel_one` = '+1-787', `country_tel_two` ='+1-939',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Qatar', `country_tel_one` = '+974',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Republic of the Congo', `country_tel_one` = '+242',`continent`='africa', `region`='central_africa';
INSERT INTO `luby_country` SET `country_name` = 'Reunion', `country_tel_one` = '+262',`continent`='africa', `region`='indian_ocean';
INSERT INTO `luby_country` SET `country_name` = 'Romania', `country_tel_one` = '+40',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Russia', `country_tel_one` = '+7',`continent`='asia', `region`='northern_asia';
INSERT INTO `luby_country` SET `country_name` = 'Rwanda', `country_tel_one` = '+250',`continent`='africa', `region`='central_asia';
INSERT INTO `luby_country` SET `country_name` = 'Saint Barthelemy', `country_tel_one` = '+590',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Saint Helena', `country_tel_one` = '+290',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Saint Kitts and Nevis', `country_tel_one` = '+1-869',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Saint Lucia', `country_tel_one` = '+1-758',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Saint Martin', `country_tel_one` = '+590',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Saint Pierre and Miquelon', `country_tel_one` = '+508',`continent`='americas', `region`='northern_america';
INSERT INTO `luby_country` SET `country_name` = 'Saint Vincent and the Grenadines', `country_tel_one` = '+1-784',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Samoa', `country_tel_one` = '+685',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'San Marino', `country_tel_one` = '+378',`continent`='europe', `region`='southern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Sao Tome and Principe', `country_tel_one` = '+239',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Saudi Arabia', `country_tel_one` = '+966',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Senegal', `country_tel_one` = '+221',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Serbia', `country_tel_one` = '+381',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Seychelles', `country_tel_one` = '+248',`continent`='africa', `region`='indian_ocean';
INSERT INTO `luby_country` SET `country_name` = 'Sierra Leone', `country_tel_one` = '+232',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Singapore', `country_tel_one` = '+65',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Sint Maarten', `country_tel_one` = '+1-721',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Slovakia', `country_tel_one` = '+421',`continent`='europe', `region`='central_europe';
INSERT INTO `luby_country` SET `country_name` = 'Slovenia', `country_tel_one` = '+386',`continent`='europe', `region`='south_east_europe';
INSERT INTO `luby_country` SET `country_name` = 'Solomon Islands', `country_tel_one` = '+677',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Somalia', `country_tel_one` = '+252',`continent`='africa', `region`='eastern_africa';
INSERT INTO `luby_country` SET `country_name` = 'South Africa', `country_tel_one` = '+27',`continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'South Korea', `country_tel_one` = '+82',`continent`='asia', `region`='east_asia';
INSERT INTO `luby_country` SET `country_name` = 'South Sudan', `country_tel_one` = '+211',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Spain', `country_tel_one` = '+34',`continent`='europe', `region`='south_west_europe';
INSERT INTO `luby_country` SET `country_name` = 'Sri Lanka', `country_tel_one` = '+94',`continent`='asia', `region`='south_asia';
INSERT INTO `luby_country` SET `country_name` = 'Sudan', `country_tel_one` = '+249',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Suriname', `country_tel_one` = '+597',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Svalbard and Jan Mayen', `country_tel_one` = '+47',`continent`='europe', `region`='northern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Swaziland', `country_tel_one` = '+268',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Sweden', `country_tel_one` = '+46',`continent`='europe', `region`='northern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Switzerland', `country_tel_one` = '+41',`continent`='europe', `region`='central_europe';
INSERT INTO `luby_country` SET `country_name` = 'Syria', `country_tel_one` = '+963',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Taiwan', `country_tel_one` = '+886',`continent`='asia', `region`='east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Tajikistan', `country_tel_one` = '+992',`continent`='asia', `region`='central_asia';
INSERT INTO `luby_country` SET `country_name` = 'Tanzania', `country_tel_one` = '+255',`continent`='africa', `region`='eastern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Thailand', `country_tel_one` = '+66',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Togo', `country_tel_one` = '+228',`continent`='africa', `region`='western_africa';
INSERT INTO `luby_country` SET `country_name` = 'Tokelau', `country_tel_one` = '+690',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Tonga', `country_tel_one` = '676',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Trinidad and Tobago', `country_tel_one` = '+1-868',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Tunisia', `country_tel_one` = '+216',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Turkey', `country_tel_one` = '+90',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Turkmenistan', `country_tel_one` = '+993',`continent`='asia', `region`='central_asia';
INSERT INTO `luby_country` SET `country_name` = 'Turks and Caicos Islands', `country_tel_one` = '+1-649',`continent`='americas', `region`='west_indies';
INSERT INTO `luby_country` SET `country_name` = 'Tuvalu', `country_tel_one` = '+688',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'U.S. Virgin Islands', `country_tel_one` = '+1-340',`continent`='americas', `region`='central_america';
INSERT INTO `luby_country` SET `country_name` = 'Uganda', `country_tel_one` = '+256',`continent`='africa', `region`='eastern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Ukraine', `country_tel_one` = '+380',`continent`='europe', `region`='eastern_europe';
INSERT INTO `luby_country` SET `country_name` = 'United Arab Emirates', `country_tel_one` = '+971',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'United Kingdom', `country_tel_one` = '+44',`continent`='europe', `region`='western_europe';
INSERT INTO `luby_country` SET `country_name` = 'United States', `country_tel_one` = '+1',`continent`='americas', `region`='north_america';
INSERT INTO `luby_country` SET `country_name` = 'Uruguay', `country_tel_one` = '+598',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Uzbekistan', `country_tel_one` = '+998',`continent`='asia', `region`='central_asia';
INSERT INTO `luby_country` SET `country_name` = 'Vanuatu', `country_tel_one` = '+678',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Vatican', `country_tel_one` = '+379',`continent`='europe', `region`='southern_europe';
INSERT INTO `luby_country` SET `country_name` = 'Venezuela', `country_tel_one` = '+58',`continent`='americas', `region`='south_america';
INSERT INTO `luby_country` SET `country_name` = 'Vietnam', `country_tel_one` = '+84',`continent`='asia', `region`='south_east_asia';
INSERT INTO `luby_country` SET `country_name` = 'Wallis and Futuna', `country_tel_one` = '+681',`continent`='oceania', `region`='pacific';
INSERT INTO `luby_country` SET `country_name` = 'Western Sahara', `country_tel_one` = '+212',`continent`='africa', `region`='northern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Yemen', `country_tel_one` = '+967',`continent`='asia', `region`='south_west_asia';
INSERT INTO `luby_country` SET `country_name` = 'Zambia', `country_tel_one` = '+260',`continent`='africa', `region`='southern_africa';
INSERT INTO `luby_country` SET `country_name` = 'Zimbabwe', `country_tel_one` = '+263',`continent`='africa', `region`='southern_africa';